## pandas file -2 continue

In [1]:
#sorting and reindexing

In [2]:
import pandas as pd

In [20]:
data = {
    "customer": ["aman", "priya", "rahul", "sneha", "karan"],
    "city": ["delhi", "mumbai", "delhi", "banglore", "mumbai"],
    "revenue":[12000, 8000,15000,7000,20000]
}

df3 = pd.DataFrame(data)
print(df3)

  customer      city  revenue
0     aman     delhi    12000
1    priya    mumbai     8000
2    rahul     delhi    15000
3    sneha  banglore     7000
4    karan    mumbai    20000

In [ ]:
# sort 

# df.sort_values(by = "column_name")
df3.sort_values(by = ["revenue", "city"])

  customer      city  revenue
3    sneha  banglore     7000
1    priya    mumbai     8000
0     aman     delhi    12000
2    rahul     delhi    15000
4    karan    mumbai    20000

In [7]:
# sort using index 

df3.sort_index()

  customer      city  revenue
0     aman     delhi    12000
1    priya    mumbai     8000
2    rahul     delhi    15000
3    sneha  banglore     7000
4    karan    mumbai    20000

In [22]:
# ressting index will give new indexing but keep the old also 

sorted_df = df3.sort_values(by = "revenue")

sorted_df.reset_index()
print(df3)

  customer      city  revenue
0     aman     delhi    12000
1    priya    mumbai     8000
2    rahul     delhi    15000
3    sneha  banglore     7000
4    karan    mumbai    20000

In [ ]:
# removing the old index

sorted_df.reset_index(drop = true)

NameError: name 'true' is not defined

In [21]:
# re indexing 

df3.reindex(4,3,1,0,2,5)

TypeError: DataFrame.reindex() takes from 1 to 2 positional arguments but 7 were given