## handling the outliers

In [2]:
import pandas as pd 
import numpy as np

In [3]:
data = {
    "Customer" : ["Aman", "Deep", "Raj", "Sneha"],
    "Age" : [25, np.nan ,40, np.nan],
    "city": ["Delhi" , "Mumbai", "Delhi" , "banglore"]
}

df = pd.DataFrame(data)
df

  Customer   Age      city
0     Aman  25.0     Delhi
1     Deep   NaN    Mumbai
2      Raj  40.0     Delhi
3    Sneha   NaN  banglore

In [7]:
df.drop_duplicates()

  Customer   Age      city
0     Aman  25.0     Delhi
1     Deep   NaN    Mumbai
2      Raj  40.0     Delhi
3    Sneha   NaN  banglore

## IQR finding

## lower bound , upper bound Q1, Q2,Q3

## We can find it using quantile(0.25) also for pandas series

# Z - Score

## Column opertions and dara transformation

1. adding column

In [9]:
data = {
    "product" : ["pen" , "notebook" , "marker"],
    "price" :[10,20,400],
    "qty": [100,400,400]
     }

df = pd.DataFrame(data)
df

    product  price  qty
0       pen     10  100
1  notebook     20  400
2    marker    400  400

In [11]:
df["Revenue"] = df["price"] * df["qty"]
df

    product  price  qty  Revenue
0       pen     10  100     1000
1  notebook     20  400     8000
2    marker    400  400   160000

### 2. apply() function , map() functions

In [13]:
df.price.map(lambda x:x*2)

0     20
1     40
2    800
Name: price, dtype: int64