## handling data in pandas

# handling the null values

In [1]:
import pandas as pd
import numpy as np

In [4]:
data = {
    "Customer" : ["Aman", "Deep", "Raj", "Sneha"],
    "Age" : [25, np.nan ,40, np.nan],
    "city": ["Delhi" , "Mumbai", "Delhi" , "banglore"]
}

df = pd.DataFrame(data)
df

  Customer   Age      city
0     Aman  25.0     Delhi
1     Deep   NaN    Mumbai
2      Raj  40.0     Delhi
3    Sneha   NaN  banglore

In [ ]:
# step -1 

df.isnull()

   Customer    Age   city
0     False  False  False
1     False   True  False
2     False  False  False
3     False   True  False

In [ ]:
## counting missing values 
# Step -2 
df.isnull().sum()

Customer    0
Age         2
city        0
dtype: int64

In [7]:
#step -3 

# Drop the row having missing value 

df.dropna()

  Customer   Age   city
0     Aman  25.0  Delhi
2      Raj  40.0  Delhi

## Filling the issing value

replace mean , median , anything

In [9]:
df["Age"].fillna(df["Age"].mean())

0    25.0
1    32.5
2    40.0
3    32.5
Name: Age, dtype: float64

In [ ]:
df.fillna(value)

## if we want to fill column with different entries we need to pass dictionary

In [ ]:
value = 44 

df.fillna({
    "name" : "Deep",
    "age" : value,
    "city" : "Banglore"
})

# Handling the missing o categorical column

# filling the Categorical data using Mode

df.["city"] = df["city"].fillna(df["city"].mode()[0])

# mode will give a list go we want highest repeating which is at o th index

df.["city"] = df["city"].fillna("Unknown")

# handle the outlier and clip it in a data set 

do this as net tsk