### Final Integrated Question (Important)
Question 15 - Mini Data Cleaning & Analysis Task

Create a dataset:

Customer, Age, City, Price, Quantity
Include:

. Missing values in Age and City
. Duplicate rows

Tasks:

1 Clean missing values
. Replace Age with mean
. Replace City with "Unknown"

2 Remove duplicate rows

3 Create new column:
Revenue = Price * Quantity

4 Filter rows where Revenue > 500

5 Sort the dataset by Revenue in descending order

6 Reset the index

7 Identify any outliers in Revenue using IQR method

In [1]:
import pandas as pd 
import numpy as np

In [17]:
data = {
    "Customer": ["John","John", "Emma", "Liam", "Olivia", "Noah",
                 "Ava", "Emma", "Sophia", "James", "Mia", "Noah"],
    "Age": [25, 25, 30, np.nan, 28, 35,
            22, 30, np.nan, 40, 27, 35],
    "City": ["Ahmedabad","Ahmedabad","Mumbai", "Delhi", np.nan, "Bangalore",
             "Ahmedabad", "Mumbai", "Pune", "Chennai", np.nan, "Bangalore"],
    "Price": [500,500, 1200, 800, 1500, 2000,
              450, 1200, 950, 5000, 700, 2000],
    "Quantity": [2,2, 1, 3, 2, 5,
                 1, 1, 2, 10, 2, 5]
}

dataset = pd.DataFrame(data)

dataset

   Customer   Age       City  Price  Quantity
0      John  25.0  Ahmedabad    500         2
1      John  25.0  Ahmedabad    500         2
2      Emma  30.0     Mumbai   1200         1
3      Liam   NaN      Delhi    800         3
4    Olivia  28.0        NaN   1500         2
5      Noah  35.0  Bangalore   2000         5
6       Ava  22.0  Ahmedabad    450         1
7      Emma  30.0     Mumbai   1200         1
8    Sophia   NaN       Pune    950         2
9     James  40.0    Chennai   5000        10
10      Mia  27.0        NaN    700         2
11     Noah  35.0  Bangalore   2000         5

In [14]:
# task:1 Cleaning the missig values :- age with mean and city with unknown
age_column = dataset["Age"]

print(age_column.isnull().sum())

city_column = dataset["City"]

print(city_column.isnull().sum())

2
2

In [18]:
# dataset["Age"] = dataset["Age"].fillna(dataset["Age"].mean())
# dataset["City"] = dataset["City"].fillna(dataset["City"].mode()[0])

dataset

dataset = dataset.fillna({
    "Age" : dataset["Age"].mean(),
    "City" : dataset["City"].mode()[0]
})

dataset

   Customer   Age       City  Price  Quantity
0      John  25.0  Ahmedabad    500         2
1      John  25.0  Ahmedabad    500         2
2      Emma  30.0     Mumbai   1200         1
3      Liam  29.7      Delhi    800         3
4    Olivia  28.0  Ahmedabad   1500         2
5      Noah  35.0  Bangalore   2000         5
6       Ava  22.0  Ahmedabad    450         1
7      Emma  30.0     Mumbai   1200         1
8    Sophia  29.7       Pune    950         2
9     James  40.0    Chennai   5000        10
10      Mia  27.0  Ahmedabad    700         2
11     Noah  35.0  Bangalore   2000         5

 ## 2. Remove duplicate rows

In [20]:
print(dataset)

dataset = dataset.drop_duplicates()

print(dataset)

   Customer   Age       City  Price  Quantity
0      John  25.0  Ahmedabad    500         2
1      John  25.0  Ahmedabad    500         2
2      Emma  30.0     Mumbai   1200         1
3      Liam  29.7      Delhi    800         3
4    Olivia  28.0  Ahmedabad   1500         2
5      Noah  35.0  Bangalore   2000         5
6       Ava  22.0  Ahmedabad    450         1
7      Emma  30.0     Mumbai   1200         1
8    Sophia  29.7       Pune    950         2
9     James  40.0    Chennai   5000        10
10      Mia  27.0  Ahmedabad    700         2
11     Noah  35.0  Bangalore   2000         5
   Customer   Age       City  Price  Quantity
0      John  25.0  Ahmedabad    500         2
2      Emma  30.0     Mumbai   1200         1
3      Liam  29.7      Delhi    800         3
4    Olivia  28.0  Ahmedabad   1500         2
5      Noah  35.0  Bangalore   2000         5
6       Ava  22.0  Ahmedabad    450         1
8    Sophia  29.7       Pune    950         2
9     James  40.0    Chennai   5000        10
10      Mia  27.0  Ahmedabad    700         2

## 3. Create new column:
Revenue = Price * Quantity

In [21]:
dataset["Revenue"] = dataset["Price"] * dataset["Quantity"]

dataset

C:\Users\Dell\AppData\Local\Temp\ipykernel_15664\3685251133.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset["Revenue"] = dataset["Price"] * dataset["Quantity"]

   Customer   Age       City  Price  Quantity  Revenue
0      John  25.0  Ahmedabad    500         2     1000
2      Emma  30.0     Mumbai   1200         1     1200
3      Liam  29.7      Delhi    800         3     2400
4    Olivia  28.0  Ahmedabad   1500         2     3000
5      Noah  35.0  Bangalore   2000         5    10000
6       Ava  22.0  Ahmedabad    450         1      450
8    Sophia  29.7       Pune    950         2     1900
9     James  40.0    Chennai   5000        10    50000
10      Mia  27.0  Ahmedabad    700         2     1400

In [22]:
dataset

   Customer   Age       City  Price  Quantity  Revenue
0      John  25.0  Ahmedabad    500         2     1000
2      Emma  30.0     Mumbai   1200         1     1200
3      Liam  29.7      Delhi    800         3     2400
4    Olivia  28.0  Ahmedabad   1500         2     3000
5      Noah  35.0  Bangalore   2000         5    10000
6       Ava  22.0  Ahmedabad    450         1      450
8    Sophia  29.7       Pune    950         2     1900
9     James  40.0    Chennai   5000        10    50000
10      Mia  27.0  Ahmedabad    700         2     1400

## 4. Filter rows where Revenue > 500

In [23]:
revenue_data = dataset[dataset["Revenue"] > 500]
print(revenue_data)

   Customer   Age       City  Price  Quantity  Revenue
0      John  25.0  Ahmedabad    500         2     1000
2      Emma  30.0     Mumbai   1200         1     1200
3      Liam  29.7      Delhi    800         3     2400
4    Olivia  28.0  Ahmedabad   1500         2     3000
5      Noah  35.0  Bangalore   2000         5    10000
8    Sophia  29.7       Pune    950         2     1900
9     James  40.0    Chennai   5000        10    50000
10      Mia  27.0  Ahmedabad    700         2     1400

## 5. Sort the dataset by Revenue in descending order

In [27]:
dataset = dataset.sort_values (by = "Revenue" , ascending= False)
dataset

   Customer   Age       City  Price  Quantity  Revenue
9     James  40.0    Chennai   5000        10    50000
5      Noah  35.0  Bangalore   2000         5    10000
4    Olivia  28.0  Ahmedabad   1500         2     3000
3      Liam  29.7      Delhi    800         3     2400
8    Sophia  29.7       Pune    950         2     1900
10      Mia  27.0  Ahmedabad    700         2     1400
2      Emma  30.0     Mumbai   1200         1     1200
0      John  25.0  Ahmedabad    500         2     1000
6       Ava  22.0  Ahmedabad    450         1      450



## 6. Reset the index

In [31]:
dataset

sorted_dataset = dataset.sort_values(by = "Revenue")
sorted_dataset.reset_index()

sorted_dataset.reset_index(drop= True)

  Customer   Age       City  Price  Quantity  Revenue
0      Ava  22.0  Ahmedabad    450         1      450
1     John  25.0  Ahmedabad    500         2     1000
2     Emma  30.0     Mumbai   1200         1     1200
3      Mia  27.0  Ahmedabad    700         2     1400
4   Sophia  29.7       Pune    950         2     1900
5     Liam  29.7      Delhi    800         3     2400
6   Olivia  28.0  Ahmedabad   1500         2     3000
7     Noah  35.0  Bangalore   2000         5    10000
8    James  40.0    Chennai   5000        10    50000


## 7. Identify any outliers in Revenue using IQR method

In [34]:
Q1 = dataset["Revenue"].quantile(0.25)
Q2 = dataset["Revenue"].quantile(0.50)
Q3 = dataset["Revenue"].quantile(0.75)

lower_bound = Q1 - 1.5*(Q3-Q1)
upper_bound = Q3 + 1.5*(Q3-Q1)

if lower_bound <0:
    lower_bound = 0

print(lower_bound , upper_bound)

0 5700.0

In [36]:
dataset[(dataset["Revenue"] < lower_bound ) | (dataset["Revenue"]>upper_bound)]

  Customer   Age       City  Price  Quantity  Revenue
9    James  40.0    Chennai   5000        10    50000
5     Noah  35.0  Bangalore   2000         5    10000