## python file 2 assignment

In [1]:
# we are going to load the dataset of the calfornia housing one any going to do all the beloew question on it

In [1]:
import pandas as pd

In [2]:
dataset = pd.read_csv("F:/Tops/python_library/pandas/csv_files/california_housing_test (1).csv")

dataset

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27,3885,661,1537,606,6.6085,344700
1,-118.30,34.26,43,1510,310,809,277,3.5990,176500
2,-117.81,33.78,27,3589,507,1484,495,5.7934,270500
3,-118.36,33.82,28,67,15,49,11,6.1359,330000
4,-119.67,36.33,19,1241,244,850,237,2.9375,81700
...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23,1450,642,1258,607,1.1790,225000
2996,-118.14,34.06,27,5257,1082,3496,1036,3.3906,237200
2997,-119.70,36.30,10,956,201,693,220,2.2895,62000
2998,-117.12,34.10,40,96,14,46,14,3.2708,162500
2999,-119.63,34.42,42,1765,263,753,260,8.5608,500001

1

Display the entire dataset.

In [5]:
print(dataset)

      longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0       -122.05     37.37                  27         3885             661
1       -118.30     34.26                  43         1510             310
2       -117.81     33.78                  27         3589             507
3       -118.36     33.82                  28           67              15
4       -119.67     36.33                  19         1241             244
...         ...       ...                 ...          ...             ...
2995    -119.86     34.42                  23         1450             642
2996    -118.14     34.06                  27         5257            1082
2997    -119.70     36.30                  10          956             201
2998    -117.12     34.10                  40           96              14
2999    -119.63     34.42                  42         1765             263

      population  households  median_income  median_house_value
0           1537         606         6.6085              344700
1            809         277         3.5990              176500
2           1484         495         5.7934              270500
3             49          11         6.1359              330000
4            850         237         2.9375               81700
...          ...         ...            ...                 ...
2995        1258         607         1.1790              225000
2996        3496        1036         3.3906              237200
2997         693         220         2.2895               62000
2998          46          14         3.2708              162500
2999         753         260         8.5608              500001

[3000 rows x 9 columns]

In [6]:
dataset.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27,3885,661,1537,606,6.6085,344700
1,-118.30,34.26,43,1510,310,809,277,3.5990,176500
2,-117.81,33.78,27,3589,507,1484,495,5.7934,270500
3,-118.36,33.82,28,67,15,49,11,6.1359,330000
4,-119.67,36.33,19,1241,244,850,237,2.9375,81700

In [7]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           3000 non-null   float64
 1   latitude            3000 non-null   float64
 2   housing_median_age  3000 non-null   int64
 3   total_rooms         3000 non-null   int64
 4   total_bedrooms      3000 non-null   int64
 5   population          3000 non-null   int64
 6   households          3000 non-null   int64
 7   median_income       3000 non-null   float64
 8   median_house_value  3000 non-null   int64
dtypes: float64(3), int64(6)
memory usage: 211.1 KB

In [8]:
dataset.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,3000.000000,3000.00000,3000.000000,3000.000000,3000.000000,3000.000000,3000.00000,3000.000000,3000.00000
mean,-119.589200,35.63539,28.845333,2599.578667,529.950667,1402.798667,489.91200,3.807272,205846.27500
std,1.994936,2.12967,12.555396,2155.593332,415.654368,1030.543012,365.42271,1.854512,113119.68747
min,-124.180000,32.56000,1.000000,6.000000,2.000000,5.000000,2.00000,0.499900,22500.00000
25%,-121.810000,33.93000,18.000000,1401.000000,291.000000,780.000000,273.00000,2.544000,121200.00000
50%,-118.485000,34.27000,29.000000,2106.000000,437.000000,1155.000000,409.50000,3.487150,177650.00000
75%,-118.020000,37.69000,37.000000,3129.000000,636.000000,1742.750000,597.25000,4.656475,263975.00000
max,-114.490000,41.92000,52.000000,30450.000000,5419.000000,11935.000000,4930.00000,15.000100,500001.00000

2

Select only the median_house_value column.

In [9]:
dataset["median_house_value"]

0       344700
1       176500
2       270500
3       330000
4        81700
         ...
2995    225000
2996    237200
2997     62000
2998    162500
2999    500001
Name: median_house_value, Length: 3000, dtype: int64

3

Select the Customer and Revenue columns together.

In [10]:
dataset[["median_income" , "median_house_value"]]

      median_income  median_house_value
0            6.6085              344700
1            3.5990              176500
2            5.7934              270500
3            6.1359              330000
4            2.9375               81700
...             ...                 ...
2995         1.1790              225000
2996         3.3906              237200
2997         2.2895               62000
2998         3.2708              162500
2999         8.5608              500001

[3000 rows x 2 columns]

4

Using loc, display the second row of the dataset.

In [13]:
dataset.loc[1]

longitude               -118.300
latitude                  34.260
housing_median_age        43.000
total_rooms             1510.000
total_bedrooms           310.000
population               809.000
households               277.000
median_income              3.599
median_house_value    176500.000
Name: 1, dtype: float64

5

Using iloc, display the third row of the dataset.

In [15]:
dataset.iloc[[2,]]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
2,-117.81,33.78,27,3589,507,1484,495,5.7934,270500

6

Using loc, retrieve the Revenue value of Rahul.

In [3]:
dataset.loc[100 , "total_rooms"]

np.int64(2120)

7

Filter the dataset to show customers whose Revenue is greater than 10000.

In [7]:
dataset.loc[dataset["total_rooms"] > 1000 , "total_bedrooms"]

0        661
1        310
2        507
4        244
5        213
        ...
2991     718
2993     510
2995     642
2996    1082
2999     263
Name: total_bedrooms, Length: 2636, dtype: int64

8

Display customers who belong to Mumbai.

In [9]:
dataset[dataset["total_bedrooms"] == 1000]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
1204,-121.64,36.8,18,5915,1000,2975,975,4.5812,255200